#!/usr/bin/env python3
"""Scan Atomic Chat / Jan GGUFs and write llama-server models-preset.ini (cross-platform)."""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Allow running as installed copy next to paths.py
sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import find_model_roots, hermes_paths, preferred_default_model  # noqa: E402

ALIAS_MAP = {
    "qwen3-coder-30b-a3b-IQ4_XS": "qwen3-coder",
    "google_gemma-3n-E4B-it-IQ4_XS": "gemma-3n",
    "Laguna-XS-2_1-Q4_K_M": "laguna-xs",
    "LFM2_5-230M-Q4_K_M": "lfm2-230m",
}


def slug_for(gguf: Path) -> str:
    folder = gguf.parent.name
    stem = gguf.stem
    # Prefer folder alias, then stem alias
    if folder in ALIAS_MAP:
        return ALIAS_MAP[folder]
    if stem in ALIAS_MAP:
        return ALIAS_MAP[stem]
    base = folder if folder and folder not in (".",) else stem
    if base.lower() in ("model", "models"):
        base = stem
    s = re.sub(r"[^\w.\-]+", "-", base).strip("-").lower()
    return s or f"model-{gguf.stat().st_size}"


def iter_ggufs(root: Path):
    """Yield complete GGUF files under root (Jan/Atomic layouts)."""
    # Atomic: .../Name/model.gguf
    for gguf in root.rglob("model.gguf"):
        yield gguf
    # Jan / other: .../name/*.gguf (not named model.gguf)
    for gguf in root.rglob("*.gguf"):
        if gguf.name == "model.gguf":
            continue
        if gguf.name.endswith(".tmp") or "mmproj" in gguf.name.lower():
            continue
        yield gguf


def is_complete(gguf: Path) -> bool:
    if not gguf.is_file():
        return False
    if gguf.name.endswith(".tmp"):
        return False
    if (gguf.parent / f"{gguf.name}.tmp").exists():
        return False
    if (gguf.parent / "model.gguf.tmp").exists() and gguf.name == "model.gguf":
        return False
    try:
        if gguf.stat().st_size < 1_000_000:
            return False
    except OSError:
        return False
    return True


def discover() -> list[dict]:
    roots = find_model_roots()
    if not roots:
        tried = "\n  ".join(str(r) for r in __import__("paths").candidate_model_roots())
        raise SystemExit(
            "No Atomic Chat / Jan models directory found.\n"
            "Looked under Application Support / APPDATA for Atomic Chat and Jan.\n"
            f"Tried:\n  {tried}\n"
            "Set ATOMIC_MODELS_DIR or JAN_MODELS_DIR to your models folder."
        )
    found: dict[str, dict] = {}
    sources: list[str] = []
    for root in roots:
        sources.append(str(root))
        for gguf in iter_ggufs(root):
            if not is_complete(gguf):
                continue
            size = gguf.stat().st_size
            sid = slug_for(gguf)
            prev = found.get(sid)
            if prev is None or size > prev["size"]:
                found[sid] = {
                    "id": sid,
                    "path": str(gguf.resolve()),
                    "size": size,
                    "folder": gguf.parent.name,
                    "root": str(root),
                }
    if not found:
        raise SystemExit(
            "No complete GGUF files found under:\n  " + "\n  ".join(sources)
        )
    return sorted(found.values(), key=lambda x: x["id"])


def write_preset(entries: list[dict]) -> Path:
    hp = hermes_paths()
    out_dir = hp["local_models"]
    preset = hp["preset"]
    catalog = hp["catalog"]
    out_dir.mkdir(parents=True, exist_ok=True)
    roots = sorted({e.get("root", "") for e in entries})
    lines = [
        f"# Auto-generated by sync_atomic_models.py at {datetime.now(timezone.utc).isoformat()}",
        f"# Sources: {'; '.join(roots)}",
        "",
        "[*]",
        "ctx-size = 65536",
        "n-gpu-layers = 99",
        "jinja = true",
        "",
    ]
    for e in entries:
        path = e["path"].replace("\\", "/")
        lines += [
            f"[{e['id']}]",
            f"model = {path}",
            "ctx-size = 65536",
            "",
        ]
    preset.write_text("\n".join(lines) + "\n", encoding="utf-8")
    catalog.write_text(json.dumps(entries, indent=2), encoding="utf-8")
    print(f"Wrote {len(entries)} models -> {preset}")
    for e in entries:
        gb = e["size"] / (1024**3)
        print(f"  {e['id']}  ({gb:.1f} GB)  {e['folder']}")
    return preset


def patch_hermes_config(entries: list[dict]) -> None:
    config = hermes_paths()["config"]
    if not config.is_file():
        print("No config.yaml to patch")
        return
    text = config.read_text(encoding="utf-8")
    original = text
    models_yaml = "\n".join(
        f"      {e['id']}:\n        context_length: 65536" for e in entries
    )
    block = (
        "custom_providers:\n"
        "  - name: atomic-local\n"
        "    base_url: http://127.0.0.1:8080/v1\n"
        "    # api_key omitted - local llama-server needs none\n"
        "    models:\n"
        f"{models_yaml}\n"
    )
    pattern = re.compile(
        r"^custom_providers:\n"
        r"  - name: atomic-local\n"
        r"(?:.*\n)*?"
        r"(?=^(?:# If local server|fallback_model:|\Z))",
        re.M,
    )
    if pattern.search(text):
        text = pattern.sub(block, text, count=1)
        print("Updated Hermes config.yaml model catalog")
    else:
        print("Note: custom_providers.atomic-local block not found; catalog.json only")

    # Keep model.default aligned with catalog (prefer qwen3-coder if present)
    default_id = preferred_default_model([e["id"] for e in entries])
    if re.search(r"^model:\n  default: ", text, re.M):
        text = re.sub(
            r"^(model:\n  default: )\S+",
            rf"\g<1>{default_id}",
            text,
            count=1,
            flags=re.M,
        )
        print(f"Updated Hermes model.default -> {default_id}")

    if text != original:
        config.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    entries = discover()
    write_preset(entries)
    patch_hermes_config(entries)
    print("Done. Restart router: python ensure_local_router.py restart")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
