#!/usr/bin/env python3
"""Scan Atomic Chat GGUFs and write llama-server models-preset.ini for router mode."""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

APPDATA = Path(os.environ.get("APPDATA", ""))
LOCALAPPDATA = Path(os.environ.get("LOCALAPPDATA", ""))
MODELS_ROOT = APPDATA / "Atomic Chat" / "data" / "llamacpp" / "models"
OUT_DIR = LOCALAPPDATA / "hermes" / "local-models"
PRESET_PATH = OUT_DIR / "models-preset.ini"
CATALOG_PATH = OUT_DIR / "catalog.json"
CONFIG_PATH = LOCALAPPDATA / "hermes" / "config.yaml"

ALIAS_MAP = {
    "qwen3-coder-30b-a3b-IQ4_XS": "qwen3-coder",
    "google_gemma-3n-E4B-it-IQ4_XS": "gemma-3n",
    "Laguna-XS-2_1-Q4_K_M": "laguna-xs",
    "LFM2_5-230M-Q4_K_M": "lfm2-230m",
}


def slug_for(gguf: Path) -> str:
    folder = gguf.parent.name
    if folder in ALIAS_MAP:
        return ALIAS_MAP[folder]
    s = re.sub(r"[^\w.\-]+", "-", folder).strip("-").lower()
    return s or f"model-{gguf.stat().st_size}"


def discover() -> list[dict]:
    if not MODELS_ROOT.is_dir():
        raise SystemExit(f"Atomic models root not found: {MODELS_ROOT}")
    found: dict[str, dict] = {}
    for gguf in MODELS_ROOT.rglob("model.gguf"):
        if not gguf.is_file():
            continue
        if (gguf.parent / "model.gguf.tmp").exists():
            continue
        size = gguf.stat().st_size
        if size < 1_000_000:
            continue
        sid = slug_for(gguf)
        prev = found.get(sid)
        if prev is None or size > prev["size"]:
            found[sid] = {
                "id": sid,
                "path": str(gguf.resolve()),
                "size": size,
                "folder": gguf.parent.name,
            }
    if not found:
        raise SystemExit(f"No complete model.gguf under {MODELS_ROOT}")
    return sorted(found.values(), key=lambda x: x["id"])


def write_preset(entries: list[dict]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Auto-generated by sync_atomic_models.py at {datetime.now(timezone.utc).isoformat()}",
        f"# Source: {MODELS_ROOT}",
        "",
        "[*]",
        "ctx-size = 65536",
        "n-gpu-layers = 99",
        "jinja = true",
        "",
    ]
    for e in entries:
        path = e["path"].replace("\\", "/")
        lines += [
            f"[{e['id']}]",
            f"model = {path}",
            "ctx-size = 65536",
            "",
        ]
    PRESET_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    CATALOG_PATH.write_text(json.dumps(entries, indent=2), encoding="utf-8")
    print(f"Wrote {len(entries)} models -> {PRESET_PATH}")
    for e in entries:
        gb = e["size"] / (1024**3)
        print(f"  {e['id']}  ({gb:.1f} GB)  {e['folder']}")


def patch_hermes_config(entries: list[dict]) -> None:
    if not CONFIG_PATH.is_file():
        print("No config.yaml to patch")
        return
    text = CONFIG_PATH.read_text(encoding="utf-8")
    models_yaml = "\n".join(
        f"      {e['id']}:\n        context_length: 65536" for e in entries
    )
    block = (
        "custom_providers:\n"
        "  - name: atomic-local\n"
        "    base_url: http://127.0.0.1:8080/v1\n"
        "    # api_key omitted - local llama-server needs none\n"
        "    models:\n"
        f"{models_yaml}\n"
    )
    pattern = re.compile(
        r"^custom_providers:\n"
        r"  - name: atomic-local\n"
        r"(?:.*\n)*?"
        r"(?=^(?:# If local server|fallback_model:|\Z))",
        re.M,
    )
    if pattern.search(text):
        text2 = pattern.sub(block, text, count=1)
        CONFIG_PATH.write_text(text2, encoding="utf-8", newline="\n")
        print("Updated Hermes config.yaml model catalog")
    else:
        print("Note: custom_providers.atomic-local block not found; catalog.json only")


def main() -> int:
    entries = discover()
    write_preset(entries)
    patch_hermes_config(entries)
    print("Done. Restart router: python ensure_local_router.py restart")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
